// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web; // fallback so app doesn’t crash on Linux

      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvOcsp3hSOegUbrw1urdwM1C1GdHZcMYc',
    appId: '1:3717070628:web:052459c63c6718bc7dbdb1',
    messagingSenderId: '3717070628',
    projectId: 'empdetails-23190',
    authDomain: 'attendiqadmin.pages.dev',
    storageBucket: 'empdetails-23190.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk5tY5MMlBR1dwZPttObtLs5hYaFAzHmc',
    appId: '1:3717070628:android:e0fab92e52e3e2df7dbdb1',
    messagingSenderId: '3717070628',
    projectId: 'empdetails-23190',
    storageBucket: 'empdetails-23190.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-3_McC2fpSMgXES6hv6zNmwVOZETarhM',
    appId: '1:3717070628:ios:414e9cd9e17aabbf7dbdb1',
    messagingSenderId: '3717070628',
    projectId: 'empdetails-23190',
    storageBucket: 'empdetails-23190.firebasestorage.app',
    iosBundleId: 'com.example.empApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-3_McC2fpSMgXES6hv6zNmwVOZETarhM',
    appId: '1:3717070628:ios:414e9cd9e17aabbf7dbdb1',
    messagingSenderId: '3717070628',
    projectId: 'empdetails-23190',
    storageBucket: 'empdetails-23190.firebasestorage.app',
    iosBundleId: 'com.example.empApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvOcsp3hSOegUbrw1urdwM1C1GdHZcMYc',
    appId: '1:3717070628:web:09fdbb79e3c51c5c7dbdb1',
    messagingSenderId: '3717070628',
    projectId: 'empdetails-23190',
    authDomain: 'attendiqadmin.pages.dev',
    storageBucket: 'empdetails-23190.firebasestorage.app',
  );
}
