import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This file will be auto-generated by FlutterFire CLI
import 'pages/admin_panel.dart';
import 'pages/employee.dart';
import 'style/employee_style.dart';
import 'pages/view.dart';
import 'pages/empdaily.dart';
import 'pages/easy.dart';
import 'account/login_page.dart';
import 'account/create_account.dart';
import 'superadmin/superadmin_panel.dart';
import 'superadmin/superview.dart';
import 'superadmin/supereasy.dart';

void main() async {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase with auto-generated options
  await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Employee Check-In System',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primaryColor: EmployeeStyle.primaryColor,
        scaffoldBackgroundColor: EmployeeStyle.backgroundColor,
        colorScheme: ColorScheme.fromSeed(
          seedColor: EmployeeStyle.primaryColor,
          secondary: EmployeeStyle.secondaryColor,
        ),
        useMaterial3: true,
      ),
      // Set EmployeePage as the first/home page
      home: const LoginPage(),
      // Optional: Add routes for navigation
      routes: {
        '/login': (context) => const LoginPage(),
        '/createAccount': (context) => const CreateAccountPage(),
        '/employee': (context) => const EmployeePage(),
        '/admin': (context) => const AdminPanel(),
        '/view': (context) => const EmployeeView(),
        '/empdaily': (context) => const EmpDailyPage(),
        '/easy': (context) => const EasyPage(),
        '/superadmin': (context) => const SuperadminPanel(),
        '/superview': (context) => const Superview(),
        '/supereasy': (context) => const Supereasy(),
      },
    );
  }
}
